function cloud-help -d "List available cloud resource lookup commands"
    echo "AWS Quick Lookups:"
    echo "  aws-ec2    - List EC2 instances"
    echo "  aws-s3     - List S3 buckets"
    echo "  aws-rds    - List RDS instances"
    echo "  aws-lambda - List Lambda functions"
    echo "  aws-eks    - List EKS clusters"
    echo ""
    echo "Azure Quick Lookups:"
    echo "  az-vm      - List Azure VMs"
    echo "  az-aks     - List AKS clusters"
    echo "  az-rg      - List Resource Groups"
    echo ""
    echo "GCP Quick Lookups:"
    echo "  gcp-gce    - List GCE instances"
    echo "  gcp-gke    - List GKE clusters"
    echo "  gcp-gcs    - List GCS buckets"
    echo ""
    echo "Cloud Context Switchers:"
    echo "  awsp       - Switch AWS profile"
    echo "  azsp       - Switch Azure subscription"
    echo "  gcpp       - Switch GCP project"
    echo ""
    echo "Kubernetes:"
    echo "  kctx       - Switch kubectl context"
    echo "  kns        - Switch kubectl namespace"
    echo "  kshell     - Start shell in a pod (-n namespace, -c container)"
    echo "  ktail      - Tail pod logs with fzf (-n namespace, -c container)"
    echo "  kclean     - Remove unreachable contexts from kubeconfig"
    echo ""
    echo "Other:"
    echo "  tws        - Switch Terraform workspace"
    echo "  cloud-ctx  - Show all current cloud contexts"
end
