function registry_help -d "Show how to use DockerHub registry credentials"
    echo "DockerHub Registry Credentials (lazy-loaded from 1Password)"
    echo ""
    echo "Functions:"
    echo "  get_registry_user      - Returns username"
    echo "  get_registry_password  - Returns password"
    echo ""
    echo "Usage examples:"
    echo "  docker login -u (get_registry_user) -p (get_registry_password)"
    echo ""
    echo "  # Set as env vars if needed:"
    echo "  set -gx BIGID_REGISTRY_USER (get_registry_user)"
    echo "  set -gx BIGID_REGISTRY_PASSWORD (get_registry_password)"
    echo ""
    echo "First call per session will prompt for 1Password auth."
end
